name: Build and Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the latest stable version

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest stable version

      # Setup AWS SAM CLI
      - name: Set up AWS SAM CLI
        uses: aws-actions/setup-sam@v2  # This action is already fine

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2  # Use the latest version of configure-aws-credentials
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      # Build the Lambda function using SAM
      - name: Build Lambda
        run: sam build --use-container  # Use container to build Lambda

      # (Optional) Run Unit Tests
      # You can insert the command to run unit tests here, e.g.:
      # - run: pytest tests/

      # Deploy the Lambda function using SAM
      - name: Deploy Lambda
        run: |
          sam deploy \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --stack-name sam-hello-world \
            --capabilities CAPABILITY_IAM \
            --s3-bucket my-sam-deployment-bucket-123 \
            --region eu-north-1 \