name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install AWS SAM
        run: |
          curl -sSL https://github.com/aws/aws-sam-cli/releases/latest/download/install | bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build and Deploy
        run: |
          sam build
          sam deploy --stack-name my-lambda-stack --capabilities CAPABILITY_IAM --no-confirm-changeset
